# Generated by Django 5.1.4 on 2024-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact_number',
            new_name='contactNumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='pin_code',
            new_name='pinCode',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
