# Generated by Django 5.1.4 on 2024-12-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_contact_number_employee_contactnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pinCode',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
